name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for contributing to this project. I give u a big beijo"
        pr-message: "Que commit e código esdrúxulo, o pior que já vi na vida reprovado e banido por ser pego fazendo lambda no python"
